FROM node:12-alpine as build

WORKDIR /usr/share/app
COPY yarn.lock package.json .yarnrc ./
COPY packages-cache ./packages-cache

RUN yarn install --frozen-lockfile --prefer-offline

COPY . .
RUN yarn build --prod mobile

FROM nginx:1.17
COPY --from=build /usr/share/app/dist/apps/mobile /usr/share/nginx/html


