version: '3'

services:
  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    environment:
      DATA_STORE: /usr/share/images/
    volumes:
      - data:/usr/share/app/data
      - images:/usr/share/images
    command: "node dist/apps/api/main.js"
    networks:
      - internal

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: .
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - front
      - internal

volumes:
  data:
  images:

networks:
  front:
    external:
      name: main
  internal:
