version: '3'

services:
  backend:
    restart: always
    volumes:
      - ./shopping-list.db:/usr/share/shopping-list.db

  frontend:
    restart: always
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: shopping.mani94.space
      LETSENCRYPT_HOST: shopping.mani94.space
      LETSENCRYPT_EMAIL: manuel.leitold@edu.fh-joanneum.at


